version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sprintsync-frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Example of how to set the backend URL via environment
    # environment:
    #   - BACKEND_URL=https://your-production-backend-url.com
    # Or pass it when running: docker-compose run -e BACKEND_URL=...
