version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: sprintsync-frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
